/* Contenido editorial de ICEMAN. Relaciona cada idea con slugs del catálogo real. */
window.ICEMAN_EDITORIAL = {
  recipes: [
    { slug:"papas-air-fryer", title:"Papas extra crujientes en Air Fryer", description:"Un acompañamiento dorado y fácil para una cena rápida o una picada en casa.", category:"Recetas", time:"8–10 min", difficulty:"Fácil", servings:"4", method:"Air Fryer", image:"air-fryer", heroImage:"editorial/hero-crispy-potatoes.webp", products:["papas-air-fryer"], tags:["papas","air fryer","rápido","partido"], ingredients:["1 funda de Papas Air Fryer ICEMAN", "Tu salsa favorita para acompañar"], steps:["Precalienta la Air Fryer a 200 °C.","Coloca las papas congeladas en la canasta, en una sola capa.","Cocina durante 8–10 minutos y agita la canasta a mitad del tiempo.","Sirve recién hechas. El tiempo puede variar según el electrodoméstico."], occasions:["peliculas","partido","cena"] },
    { slug:"picada-para-compartir", title:"Picada ICEMAN para compartir", description:"Arma una mesa variada con bocados del catálogo y deja que cada persona elija su favorito.", category:"Recetas", time:"20 min aprox.", difficulty:"Fácil", servings:"4–6", method:"Air Fryer u horno", image:"aros-cebolla", products:["aros-de-cebolla","hash-brown","papas-air-fryer"], tags:["picada","snacks","reunión","partido"], ingredients:["Aros de cebolla ICEMAN", "Hash Brown ICEMAN", "Papas Air Fryer ICEMAN", "Salsas para servir"], steps:["Revisa las indicaciones de preparación de cada producto.","Prepara cada opción por separado, respetando su tiempo y temperatura.","Sirve en una fuente amplia con las salsas al centro.","Lleva a la mesa apenas esté listo."], occasions:["reunion","partido","peliculas"] },
    { slug:"hamburguesa-con-papas", title:"Hamburguesa con papas estilo restaurante", description:"Una combinación clásica para una cena en casa con papas ICEMAN recién preparadas.", category:"Recetas", time:"12–15 min para las papas", difficulty:"Fácil", servings:"4", method:"Air Fryer o sartén", image:"papas-ondulado-premium", products:["corte-ondulado-900-premium"], tags:["papas","hamburguesa","cena"], ingredients:["Papas corte ondulado ICEMAN", "Hamburguesas y panes de tu elección", "Tus acompañamientos favoritos"], steps:["Prepara las hamburguesas a tu gusto.","Mientras tanto, cocina las papas congeladas según las instrucciones del empaque.","Arma las hamburguesas con los acompañamientos que prefieras.","Sirve todo caliente."], occasions:["cena","fin-de-semana"] },
    { slug:"noche-de-alitas-y-papas", title:"Noche de alitas y papas", description:"Una idea sencilla para compartir el partido o una película en casa.", category:"Recetas", time:"12–15 min para las papas", difficulty:"Fácil", servings:"4", method:"Air Fryer", image:"papas-spices", products:["papas-spices","papas-air-fryer","aros-de-cebolla"], tags:["partido","película","papas","reunión"], ingredients:["Papas ICEMAN a elección", "Alitas de tu preferencia", "Salsas para acompañar"], steps:["Prepara las alitas siguiendo las instrucciones de su empaque.","Cocina las papas ICEMAN congeladas según el modo indicado.","Dispón alitas, papas y salsas en una fuente para compartir."], occasions:["partido","peliculas"] },
    { slug:"desayuno-con-waffles", title:"Desayuno fácil con waffles", description:"Waffles listos en minutos para acompañar con fruta o lo que tengas a mano.", category:"Recetas", time:"5–6 min", difficulty:"Fácil", servings:"2", method:"Horno", image:"waffle", products:["waffle-glaseado"], tags:["desayuno","waffle","rápido"], ingredients:["Waffles glaseados ICEMAN", "Fruta fresca para acompañar, opcional"], steps:["Precalienta el horno a 200 °C.","Coloca los waffles congelados en una bandeja.","Hornea durante 5–6 minutos y sirve."], occasions:["fin-de-semana","cena"] }
  ],
  articles: [
    { slug:"congelado-y-nutrientes", title:"¿Los alimentos congelados pierden sus nutrientes?", category:"Nutrición", description:"Una guía breve para entender la ultracongelación y leer la información de cada producto.", image:"mix-jardinera", products:["mix-jardinera-450"], tags:["nutrición","vegetales","congelado"], body:["La congelación es un método de conservación. El perfil nutricional depende de cada alimento y de cómo fue procesado; para conocer un producto, revisa su etiqueta e ingredientes.","En el catálogo ICEMAN, los vegetales ultracongelados IQF se describen como precocidos o listos para preparar según el producto. Sigue siempre las instrucciones de su empaque."] },
    { slug:"fresco-o-congelado", title:"Congelado o fresco: qué cambia realmente", category:"Nutrición", description:"Cada formato tiene características distintas. La etiqueta ayuda a elegir con información clara.", image:"arvejas", products:["arvejas-450"], tags:["nutrición","vegetales","congelado"], body:["Fresco y congelado describen formas distintas de conservación. El origen, el procesamiento y el tiempo de almacenamiento influyen en las características de cada alimento.","Compara ingredientes, porción e información nutricional en el empaque del producto específico. No todos los alimentos tienen la misma composición."] },
    { slug:"leer-tabla-nutricional", title:"Cómo leer una tabla nutricional", category:"Nutrición", description:"Porción, ingredientes y valores: una forma práctica de orientarte al revisar un empaque.", image:"maiz-dulce", products:["maiz-dulce-450"], tags:["nutrición","etiqueta","productos"], body:["Empieza por el tamaño de porción: los valores de la tabla corresponden a esa cantidad. Si consumes más o menos, los valores cambian proporcionalmente.","Lee también la lista de ingredientes y las indicaciones de conservación. Consulta el empaque de cada producto para sus datos específicos."] },
    { slug:"cadena-de-frio", title:"Cómo conservar correctamente los congelados", category:"Consejos", description:"La cadena de frío ayuda a conservar los productos durante el almacenamiento y traslado.", image:"edamame-vaina", products:["edamame-vaina"], tags:["conservación","cadena de frío","congelado"], body:["El catálogo ICEMAN indica mantener los productos congelados a −18 °C. Guárdalos en el congelador al llegar a casa y revisa siempre la información del empaque.","Evita dejar productos congelados a temperatura ambiente. Sigue las instrucciones de conservación y preparación de cada producto."] }
  ],
  occasions: [
    { slug:"peliculas", title:"Noche de películas", text:"Prepara algo para picar y disfruta la función en casa.", image:"hash-brown", products:["papas-air-fryer","aros-de-cebolla","hash-brown"], tags:["snacks","reunión"] },
    { slug:"partido", title:"Partido con amigos", text:"Una picada variada para acompañar cada jugada.", image:"papas-ondulado-premium", products:["papas-air-fryer","aros-de-cebolla","hash-brown"], tags:["picada","reunión"] },
    { slug:"reunion", title:"Reunión en casa", text:"Opciones para poner al centro y compartir sin complicaciones.", image:"croqueta-yuca", products:["croqueta-de-yuca","aros-de-cebolla","papas-spices"], tags:["picada","snacks"] },
    { slug:"cena", title:"Cena rápida", text:"Resuelve el acompañamiento y adapta el plato a tu gusto.", image:"papas-finas-hierbas", products:["papas-air-fryer","mix-jardinera-450","waffle-glaseado"], tags:["rápido","cena"] },
    { slug:"fin-de-semana", title:"Fin de semana", text:"Ideas fáciles para un desayuno tranquilo o una comida en familia.", image:"waffle", products:["papas-air-fryer","waffle-glaseado","pizza-jamon-queso"], tags:["familia","desayuno"] }
  ],
  business: [
    { slug:"elegir-congelados-restaurante", title:"Cómo elegir productos congelados para tu restaurante", description:"Criterios prácticos para revisar formatos, preparación y variedad según tu operación.", category:"Para tu negocio", image:"papas-ondulado-premium", tags:["restaurante","operación"], body:["Empieza por el menú y el ritmo de servicio: identifica qué preparaciones podrían beneficiarse de opciones listas para cocinar.","Revisa presentación, unidades por caja, métodos de preparación y condiciones de almacenamiento en la ficha de cada producto. La disponibilidad se confirma con el equipo comercial."] },
    { slug:"costo-por-porcion", title:"Cómo calcular el costo por porción", description:"Un cálculo sencillo puede ayudarte a comparar presentaciones para tu menú.", category:"Para tu negocio", image:"papas-recto-premium", tags:["costos","restaurante"], body:["Divide el costo de compra por la cantidad de porciones que obtienes según el gramaje que sirves. Registra también mermas y otros ingredientes de la preparación.","El resultado depende de la presentación y del tamaño de porción de tu negocio. Consulta con el equipo ICEMAN sobre los formatos disponibles."] },
    { slug:"organizar-cadena-de-frio", title:"Cadena de frío: buenas prácticas para tu operación", description:"Organiza almacenamiento y manipulación siguiendo las indicaciones del producto.", category:"Para tu negocio", image:"edamame-grano", tags:["cadena de frío","operación"], body:["Planifica la recepción y el almacenamiento para mantener los productos congelados. El catálogo ICEMAN indica conservación a −18 °C.","Verifica la temperatura del congelador y sigue las instrucciones de conservación de cada empaque. Ajusta tus procedimientos a las normas aplicables a tu establecimiento."] },
    { slug:"simplificar-preparacion-menu", title:"Ideas para simplificar la preparación de tu menú", description:"Explora formatos y métodos de preparación del catálogo según las necesidades de tu cocina.", category:"Para tu negocio", image:"hash-brown", tags:["cafetería","operación"], body:["Compara los métodos indicados en las fichas del catálogo: algunos productos ofrecen preparación en Air Fryer, horno, freidora o sartén.","Cuéntanos qué tipo de negocio tienes y qué categorías buscas. El equipo comercial puede compartir información sobre presentaciones y opciones para tu operación."] }
  ]
};
